version: "3.9"

services:

  message-broker:
    image: rabbitmq:3.12-management
    container_name: message-broker
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 5672:5672
      - 15672:15672
    restart: always