name: Main

on:
    push:
        branches: ['master']

jobs:
    build-app:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.21.0'

        - name: Install dependencies
          run: |
            go get github.com/streadway/amqp@v1.1.0

        - name: Build
          run: go build -v ./...

    all-tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: testing
          run: go test -v ./...